---
title: "Publications"
output: distill::distill_article
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## List of Publications

1.	**Ipe, R. M**.; Nag, P.; Mori, S.; Nambiar, A. P.; Reddy, V. S.; Gokulnath, S. Synthesis, Structure and Optical Properties of a Bis-Macrocycle Derived from a Highly Emissive 1,3,6,8-Tetra(1H-pyrrole-2-yl)pyrene. J. Org. Chem. 2022, 87, 15022-15030.  
2.	**Ipe, R. M**.; Parammal, A.; Nag, P.; Mori, S.; Nambiar, A. P.; Reddy, V. S.; Gokulnath, S. Synthetic Model for FRET Constructed from Covalently Linked Porphyrin Dimers via Pyrene Bridge. J. Org. Chem. 2023, 88, 5780-5790. 
3.	**Ipe, R. M**.; Nambiar, A. P.; Nag, P.; Reddy, V. S.; Gokulnath, S. Unprecedented formation of bis-Calix[5]phyrins centrally linked with pyrene subunits. J.Porphyrins Phthalocyanines. 2023, 27, 1203-1211
4.	**Ipe, R. M**.; Kamalini, S.; Sahla, N. C. P.; Gokulnath, S. 5,15-A2BC Type Donor Acceptor Porphyrin Systems Bearing Two Different Polycyclic Aromatic Hydrocarbons. Manuscript prepared.  
5.	Nambiar, A. P.; Nag, P.; **Ipe, R. M**.; Reddy, V. S.; Gokulnath, S. Conformationally Conformationally Locked Cyclo[2]Dipyrrins Linked with Anthracene Subunits: Synthesis and Chiroptical Properties. Angew. Chem. Int. Ed. 2023 e202306566. doi:10.1002/anie.202306566.


